### ISSUE TITLE
没有做压缩处理吗

### ISSUE THREAD

**Issue by Adgeros** [pye52/Recorder#1]

**Comment by pye52** [comment]
可以自己调源码的参数来控制大小
实际上录制10s的视频大小也就1、2m，所以觉得不需要再进行压缩了

**Comment by ShengJunHu** [comment]
压缩需要做的，看你用什么手机录制的，有些手机10s中能达到24MB

**Comment by pye52** [comment]
恩，会做，但是现阶段先把该实现的做好…
